name: Cirrus clouds GPU

on:
  push:
    branches:
      - "gpu-opt"
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: gha-runner-cm1-gpu
    container:
      image:  cmille73/mpas-nvidia:carlp-mpich
      options: --gpus all
    steps:
      - uses: actions/checkout@v3

      - name: 
        run: |
           cd src/
           make -j 4 FC=nvfortran USE_OPENACC=true USE_MPI=true
           cd ../run
           mpiexec -n 4 ./cm1.exe

